[site]
name = "my-site"
url = "https://example.com"
language = "en"

[build]
output = "build/"
minify = true
inlinecss = true

[server]
port = 3000
workers = 0
admin = false
# corsorigins = "http://localhost:11432"

[store]
backend = "flat"

[log]
accessformat = "combined"

[paths]
apiprefix = ""

[requires]
mintoke = "2.0.0"
