#!/bin/sh
# gen_app_makefile.sh — Generate a Makefile for an ooke application.
#
# Scans pages/ for handler modules, generates _handlers.tk and _main.tk,
# and produces a Makefile that compiles everything into a per-app binary.
#
# Usage: ./gen_app_makefile.sh <project_dir> [ooke_dir] [toke_dir]
#
# Output: <project_dir>/Makefile.serve (generated build file)

set -e

PROJECT="${1:-.}"
OOKE_DIR="${2:-/Users/matthew.watt/tk/toke-ooke}"
TOKE_DIR="${3:-/Users/matthew.watt/tk/toke}"

APP_NAME=$(grep 'name' "$PROJECT/ooke.toml" 2>/dev/null | head -1 | sed 's/.*= *"//; s/".*//' || echo "app")
[ -z "$APP_NAME" ] && APP_NAME="app"

# Step 1: Generate _handlers.tk
"$OOKE_DIR/scripts/gen_handlers.sh" "$PROJECT/pages" "$PROJECT/_handlers.tk"

# Step 2: Collect page handler .tk files
PAGE_HANDLERS=""
for tkfile in $(find "$PROJECT/pages" -name '*.tk' -type f 2>/dev/null | sort); do
  has_get=0; has_post=0
  grep -q 'f=get(' "$tkfile" 2>/dev/null && has_get=1
  grep -q 'f=post(' "$tkfile" 2>/dev/null && has_post=1
  if [ "$has_get" -eq 1 ] || [ "$has_post" -eq 1 ]; then
    PAGE_HANDLERS="$PAGE_HANDLERS $tkfile"
  fi
done

# Step 3: Generate _serve_main.tk
cat > "$PROJECT/_serve_main.tk" << MAIN
m=app.main;
i=http:std.http;
i=log:std.log;
i=str:std.str;
i=path:std.path;
i=args:std.args;
i=config:ooke.config;
i=serve:ooke.serve;
i=handlers:ooke.handlers;

f=main():i64{
  let count=args.count() as i64;
  let projectdir=mt args.get(1 as u64) {Ok:v v;Err:e "."};
  let cfg=mt config.configload(path.join(projectdir;"ooke.toml")) {Ok:v v;Err:e config.cfgdefault()};
  let handledpaths=handlers.registerall();
  (log.info(str.concat("registered ";str.concat(str.fromint(handledpaths.len);" handler routes"));@()));
  let r=mt serve.serverun(projectdir;cfg.serverport;cfg.serverworkers;cfg.buildoutput;"";"";cfg.sitename;cfg.siteurl;cfg.sitelanguage;cfg.apiprefix;cfg.servercorsorigins;handledpaths) {Ok:v 0;Err:e 1};
  <r
};
MAIN

# Step 4: Generate Makefile.serve
OOKE_MODS="config store router template validate repair serve"
OOKE_LL=""
for m in $OOKE_MODS; do
  OOKE_LL="$OOKE_LL $OOKE_DIR/src/ooke/$m"
done

PAGE_LL=""
PAGE_TKI_RULES=""
for tkfile in $PAGE_HANDLERS; do
  modpath=$(grep '^m=' "$tkfile" | head -1 | sed 's/m=//; s/;//')
  modname=$(echo "$modpath" | sed 's/.*\.//')
  PAGE_LL="$PAGE_LL build/ooke/$modname"
  PAGE_TKI_RULES="${PAGE_TKI_RULES}
build/ooke/${modname}.tki build/ooke/${modname}: ${tkfile} | build/ooke
	cd \$(PROJECT) && \$(TKC) --emit-interface --emit-llvm --out build/ooke/${modname} ${tkfile#$PROJECT/}
"
done

cat > "$PROJECT/Makefile.serve" << MAKEFILE
# Generated by ooke — per-app serve binary build
# Regenerate with: $OOKE_DIR/scripts/gen_app_makefile.sh $PROJECT

TKC         := $TOKE_DIR/toke
TOKE_STDLIB := $TOKE_DIR/src/stdlib
TOKE_VENDOR := $TOKE_DIR/stdlib/vendor
OOKE_DIR    := $OOKE_DIR
PROJECT     := $PROJECT

BIN := build/$APP_NAME

STDLIB_SRCS := \\
  \$(TOKE_STDLIB)/str.c \\
  \$(TOKE_STDLIB)/file.c \\
  \$(TOKE_STDLIB)/env.c \\
  \$(TOKE_STDLIB)/log.c \\
  \$(TOKE_STDLIB)/http.c \\
  \$(TOKE_STDLIB)/router.c \\
  \$(TOKE_STDLIB)/encoding.c \\
  \$(TOKE_STDLIB)/tk_web_glue.c \\
  \$(TOKE_STDLIB)/tk_runtime.c \\
  \$(TOKE_STDLIB)/args.c \\
  \$(TOKE_STDLIB)/path.c \\
  \$(TOKE_STDLIB)/md.c \\
  \$(TOKE_STDLIB)/toml.c \\
  \$(TOKE_STDLIB)/process.c \\
  \$(TOKE_STDLIB)/task.c \\
  \$(TOKE_STDLIB)/collections.c

CMARK_SRCS := \$(filter-out \$(TOKE_VENDOR)/cmark/src/main.c, \$(wildcard \$(TOKE_VENDOR)/cmark/src/*.c))
TOML_SRCS  := \$(TOKE_VENDOR)/tomlc99/toml.c
VENDOR_SRCS := \$(CMARK_SRCS) \$(TOML_SRCS)

CFLAGS := -std=c99 -D_GNU_SOURCE -O1 -iquote \$(TOKE_STDLIB) \\
          -I\$(TOKE_VENDOR)/cmark/src -I\$(TOKE_VENDOR)/tomlc99 \\
          -Wno-pedantic -DTK_HAVE_OPENSSL
LIBS := -lssl -lcrypto -lz -lm -lsqlite3

UNAME := \$(shell uname -s)
ifeq (\$(UNAME), Darwin)
  CFLAGS  += -I/opt/homebrew/include
  LDFLAGS += -L/opt/homebrew/lib
endif

# ooke library modules (pre-compiled)
OOKE_LL := $OOKE_LL

# App page handler modules
PAGE_LL := $PAGE_LL

.PHONY: all clean

all: \$(BIN)

build/ooke:
	mkdir -p build/ooke

# Page handler compilation rules
$PAGE_TKI_RULES
# Generated handlers module
build/ooke/handlers.tki build/ooke/handlers: _handlers.tk \$(addsuffix .tki,\$(PAGE_LL)) | build/ooke
	cd \$(PROJECT) && \$(TKC) --emit-interface --emit-llvm --out build/ooke/handlers _handlers.tk

# Main entry point
build/main.ll: _serve_main.tk build/ooke/handlers.tki \$(OOKE_DIR)/src/ooke/config.tki \$(OOKE_DIR)/src/ooke/serve.tki | build/ooke
	cd \$(PROJECT) && \$(TKC) --emit-llvm --out build/main.ll _serve_main.tk

# Final binary
\$(BIN): build/main.ll build/ooke/handlers \$(PAGE_LL) | build/ooke
	clang \$(CFLAGS) \$(LDFLAGS) \\
	  -x ir build/main.ll build/ooke/handlers \$(PAGE_LL) \$(OOKE_LL) \\
	  -x c \$(STDLIB_SRCS) \$(VENDOR_SRCS) \\
	  -o \$@ \$(LIBS)

clean:
	rm -rf build/
MAKEFILE

echo "Generated: $PROJECT/Makefile.serve"
echo "Build with: make -f Makefile.serve"
echo "Run with: build/$APP_NAME ."
