[site]
name = "testproj"
url = ""
language = "en"

[build]
output = "build/"
minify = true
inlinecss = true

[server]
port = 8092
workers = 4

[store]
backend = "flat"

[log]
accessformat = "combined"
maxlines = 10000
maxagedays = 30
